{% set version = "2021.9.1" %}

package:
  name: dask-core
  version: {{ version }}

source:
  fn: dask-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: e11f2bf2cac809e5408fc107dcf727af3bc3472160f206cb4b828211396ad65c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - wheel

  run:
    - python >=3.7
    - packaging >=20.0
    - cloudpickle >=1.1.1
    - fsspec >=0.6.0
    - partd >=0.3.10
    - pyyaml
    - toolz >=0.8.2

test:
  imports:
    - dask
  requires:
    - pip
  commands:
    - pip check

#Note: The build and dependency order for dask-distributed packages are as follows.
#      dask-core --->distributed --->dask

about:
  home: http://github.com/dask/dask/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Parallel Python with task scheduling
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - shoyer
    - sinhrks
    - tomaugspurger
    - jrbourbeau
