{% set name = "dask-core" %}
{% set version = "2025.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.split('-')[0] }}/{{ name.split('-')[0] }}-{{ version }}.tar.gz
  sha256: 8d478f2aabd025e2453cf733ad64559de90cf328c20209e4574e9543707c3e1b

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - dask = dask.__main__:main

# Please note the repo used is the same as `dask`
# Only the minimum reqs needed to build `dask` go here
# Optional dependencies should exist in `dask` recipe
requirements:
  host:
    - python
    - pip
    - setuptools >=80
    - versioneer 0.29
    - tomli
    - setuptools-scm >=9
  run:
    - python
    - click >=8.1
    - cloudpickle >=3.0.0
    - fsspec >=2021.09.0
    - packaging >=20.0
    - partd >=1.4.0
    - pyyaml >=5.3.1
    - toolz >=0.12.0
    - importlib-metadata >=4.13.0  # [py<312]
  run_constrained:
    - numpy >=1.24
    - pyarrow >=14.0.1
    - lz4 >=4.3.2
    - pandas >=2.0
    - bokeh >=3.1.0
    - jinja2 >=2.10.3
    - distributed >=2025.12.0,<2025.12.1

# Tests must be added in the dask recipe:
# https://github.com/AnacondaRecipes/dask-feedstock/blob/master/recipe/meta.yaml
test:
  source_files:
    - dask/tests
    - dask/dask.yaml
    - dask/dask-schema.yaml
  imports:
    - dask
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v dask/tests -k "not (test_register_command_ep)"

# Note: The build and dependency order for dask-distributed packages are as follows.
# dask-core -> dask-expr -> distributed -> dask
about:
  home: https://github.com/dask/dask
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Parallel Python with task scheduling
  description: Dask is a flexible parallel computing library for analytics.
  doc_url: https://docs.dask.org
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - shoyer
    - sinhrks
    - tomaugspurger
    - jrbourbeau
  skip-lints:
    - python_build_tool_in_run
    - host_section_needs_exact_pinnings
