{% set version = "2.18.1" %}

package:
  name: dask-core
  version: {{ version }}

source:
  fn: dask-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: 8ed21e2344419fad7c6f648123f6f56cf2480d0ac4fae92d9063adb321f1c490

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - pyyaml

test:
  imports:
    - dask

about:
  home: http://github.com/dask/dask/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Parallel Python with task scheduling
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - shoyer
    - sinhrks
    - tomaugspurger
    - jrbourbeau
