{% set name = "dask-core" %}
{% set version = "2025.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: 979d9536549de0e463f4cab8a8c66c3a2ef55791cd740d07d9bf58fab1d1076a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

# Please note the repo used is the same as `dask`
# Only the minimum reqs needed to build `dask` go here
# Optional dependencies should exist in `dask` recipe
requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=62.6
    - versioneer 0.29
    - toml
  run:
    - python
    - click >=8.1
    - cloudpickle >=3.0.0
    - fsspec >=2021.09.0
    - packaging >=20.0
    - partd >=1.4.0
    - pyyaml >=5.3.1
    - toolz >=0.10.0
    - importlib-metadata >=4.13.0  # [py<312]
  run_constrained:
    # array
    - numpy >=1.24
    # dataframe
    - pandas >=2.0
    - pyarrow >=14.0.1
    # diagnostics
    - bokeh >=3.1.0
    - jinja2 >=2.10.3
    # complete
    # - pyarrow >=14.0.1
    - lz4 >= 4.3.2

test:
  imports:
    - dask
  commands:
    - pip check
  requires:
    - pip

#Note: The build and dependency order for dask-distributed packages are as follows.
#      dask-core ---> dask-expr --->distributed --->dask

about:
  home: https://www.dask.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Parallel Python with task scheduling
  description: |
    Dask is a flexible parallel computing library for analytics.
  doc_url:  https://docs.dask.org
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - shoyer
    - sinhrks
    - tomaugspurger
    - jrbourbeau
  skip-lints:
    - python_build_tool_in_run
    - host_section_needs_exact_pinnings
