{% set version = "2021.5.1" %}

package:
  name: dask-core
  version: {{ version }}

source:
  fn: dask-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: 4f2a0f67cc99ca511cefa0a7d383870807776a17c26a8da788dafb68ab552079

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - wheel

  run:
    - python >=3.7
    - cloudpickle >=1.1.1
    - fsspec >=0.6.0
    - partd >=0.3.10
    - pyyaml
    - toolz >=0.8.2

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.io
    - dask.dataframe.tseries
    - dask.diagnostics
  requires:
    - pip
  commands:
    - pip ckeck

about:
  home: http://github.com/dask/dask/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Parallel Python with task scheduling
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - shoyer
    - sinhrks
    - tomaugspurger
    - jrbourbeau
