{% set name = "dask-core" %}
{% set version = "2023.2.0" %}
{% set checksum = "c0716193e0e197bc541199e41770b4f2f7df6c137bb94e5b4812cfdc6cbe0a84" %}
{% set build_number = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: dask-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: {{ build_number }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.8
    - cloudpickle >=1.1.1
    - fsspec >=0.6.0
    - packaging >=20.0
    - partd >=0.3.10
    - pyyaml >=5.3.1
    - toolz >=0.8.2

test:
  imports:
    - dask
  requires:
    - pip
  commands:
    - pip check || true   # [not win]
    - pip check || 1      # [win]

#Note: The build and dependency order for dask-distributed packages are as follows.
#      dask-core --->distributed --->dask

about:
  home: https://github.com/dask/dask/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Parallel Python with task scheduling
  doc_url: https://dask.org/
  doc_source_url: https://github.com/dask/dask/tree/main/docs
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - shoyer
    - sinhrks
    - tomaugspurger
    - jrbourbeau
