travis:
  secure:
    BINSTAR_TOKEN: iARr0thmKNqUNnf5PXJoE4in5AOldBMiJkFTDkJM2BiU7pBsbkD8obcEHaDEljsgmRGsjR4SjobDQYwRiT7rvfSoZVw3FVUf/G59Kxq3UdkSqoM5ieTq11qk6vy3TmWFtdyLr/LA6vTJZbbcIbcFlVhK7yshvqr9WrbYzCvZjc6odUk1QSxTitGDL7/wCs3OZoQCvQUABIPI47ANnHpbfjoSXLCVUs3bBDOJjMp+NKf1WR7EkvByA50uGQi7gLkIIfTEQtDgUNOf2xS+bmRXKkrlDZGOdSEpiMRWAxsPBk4NSJX3Qag3TwirEsjJnVDsRI1OqYwXDGwO6lCReFaVTQ/zRIdrZyAfsyKGVodQuw8nwqtLTh+QRO8sgzodi8nmgzKuCXwXAa/gLfVjlq+CCvXVE1TVmDTNdb6ckpjiL4o2nHOZeyIiq1DsU/RVY7emPajywPsNCbVOuEqhAgql1+wsaC1BacBSPB3by94qX51PSNF1dGF+F9XlyM9lONnzvZO41a3DisLTDiaoroSOdezp/wXdze4b2g/PudHMSlIMaLLrEYfe2pWppwcPAccfTKsJuHp/Pn65aDMRYMZ7gmgR2LVMMjoqoCqtnovJ4afuRDuYtPBswDQoEIHqwOB0LkCDWjG3Vtj3iYPN5kNLtsMrvav7a0qT/xSyoeTAp4I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
